version: '3.8'

services:
  billing-service:
    build:
      context: ./services/billing-service
    container_name: billing-service
    ports:
      - "5102:8080"   # outside:inside (Billing listens on 8080 in container)
    # if Billing needs env vars, add them here
    # environment:
    #   - ASPNETCORE_ENVIRONMENT=Production

  booking-service:
    build:
      context: ./services/booking-service
    container_name: booking-service
    ports:
      - "8000:8000"   # outside:inside
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017

  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
